language: python
python:
  - "3.6"
cache: pip
# install:
#   - pip install -r requirements.txt
script:
  - python tests.py
deploy:
  provider: lambda
  function_name: "ucsb-sa-ssis-hero-villan-sample-api"
  region: "us-west-2"
  role: "arn:aws:iam::035849207430:role/service-role/ucsb-sa-ssis-hero-villan-sample-api-role-uyunq8mw"
  runtime: "python3.7"
  handler_name: "handler"
